name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos
        uses: actions/checkout@v3.5.3

      - name: Instalar python
        uses: actions/setup-python@v3.1.4
        with:
          python-version : '3.10' 

      - name: Instalar Poetry
        run: pip install poetry

      - name: Setando v-envs
        env:
          TWILIO_AUTH_TOKEN: ${{ secret.TWILIO_AUTH_TOKEN }}
          TWILIO_ACCOUNT_SID: ${{ secret.TWILIO_ACCOUNT_SID }}
          TWILIO_DESTINY_PHONE_NUMBER: ${{ secret.TWILIO_DESTINY_PHONE_NUMBER }}
          TWILIO_PHONE_NUMBER: ${{ secret.TWILIO_PHONE_NUMBER }}
        run: echo "v-envs setadas."

      - name: Instalar dependências do projeto
        run: poetry install --without doc --no-ansi

      - name: Rodar testes
        run: poetry run task test