name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos
        uses: actions/checkout@v4

      - name: Instalar python
        uses: actions/setup-python@v5
        with:
          python-version : '3.10' 

      - name: Instalar Poetry
        run: pip install poetry

      - name: Criar arquivo
        run: touch .env

      - name: Setando v-env
        run: echo BOT_TOKEN="${{ secrets.BOT_TOKEN }}" >> .env
      - name: Setando v-env
        run: echo BOT_ID="${{ secrets.BOT_ID }}" >> .env

      - name: Instalar dependências do projeto
        run: poetry install --without doc --no-ansi

      - name: Rodar testes
        run: poetry run task test --cov-report=xml

      - name: Subir cobertura Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
